eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: index-codes-service
  redis:
    database: 0
    host: 120.79.27.130
    password:
    port: 6379