eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: third-part-index-data-project
  redis:
    database: 0
    host: 120.79.27.130
    password:
    port: 6379